// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package security_config

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.IAMIdentityCenterOptions, b.ko.Spec.IAMIdentityCenterOptions) {
		delta.Add("Spec.IAMIdentityCenterOptions", a.ko.Spec.IAMIdentityCenterOptions, b.ko.Spec.IAMIdentityCenterOptions)
	} else if a.ko.Spec.IAMIdentityCenterOptions != nil && b.ko.Spec.IAMIdentityCenterOptions != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.IAMIdentityCenterOptions.GroupAttribute, b.ko.Spec.IAMIdentityCenterOptions.GroupAttribute) {
			delta.Add("Spec.IAMIdentityCenterOptions.GroupAttribute", a.ko.Spec.IAMIdentityCenterOptions.GroupAttribute, b.ko.Spec.IAMIdentityCenterOptions.GroupAttribute)
		} else if a.ko.Spec.IAMIdentityCenterOptions.GroupAttribute != nil && b.ko.Spec.IAMIdentityCenterOptions.GroupAttribute != nil {
			if *a.ko.Spec.IAMIdentityCenterOptions.GroupAttribute != *b.ko.Spec.IAMIdentityCenterOptions.GroupAttribute {
				delta.Add("Spec.IAMIdentityCenterOptions.GroupAttribute", a.ko.Spec.IAMIdentityCenterOptions.GroupAttribute, b.ko.Spec.IAMIdentityCenterOptions.GroupAttribute)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.IAMIdentityCenterOptions.InstanceARN, b.ko.Spec.IAMIdentityCenterOptions.InstanceARN) {
			delta.Add("Spec.IAMIdentityCenterOptions.InstanceARN", a.ko.Spec.IAMIdentityCenterOptions.InstanceARN, b.ko.Spec.IAMIdentityCenterOptions.InstanceARN)
		} else if a.ko.Spec.IAMIdentityCenterOptions.InstanceARN != nil && b.ko.Spec.IAMIdentityCenterOptions.InstanceARN != nil {
			if *a.ko.Spec.IAMIdentityCenterOptions.InstanceARN != *b.ko.Spec.IAMIdentityCenterOptions.InstanceARN {
				delta.Add("Spec.IAMIdentityCenterOptions.InstanceARN", a.ko.Spec.IAMIdentityCenterOptions.InstanceARN, b.ko.Spec.IAMIdentityCenterOptions.InstanceARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.IAMIdentityCenterOptions.UserAttribute, b.ko.Spec.IAMIdentityCenterOptions.UserAttribute) {
			delta.Add("Spec.IAMIdentityCenterOptions.UserAttribute", a.ko.Spec.IAMIdentityCenterOptions.UserAttribute, b.ko.Spec.IAMIdentityCenterOptions.UserAttribute)
		} else if a.ko.Spec.IAMIdentityCenterOptions.UserAttribute != nil && b.ko.Spec.IAMIdentityCenterOptions.UserAttribute != nil {
			if *a.ko.Spec.IAMIdentityCenterOptions.UserAttribute != *b.ko.Spec.IAMIdentityCenterOptions.UserAttribute {
				delta.Add("Spec.IAMIdentityCenterOptions.UserAttribute", a.ko.Spec.IAMIdentityCenterOptions.UserAttribute, b.ko.Spec.IAMIdentityCenterOptions.UserAttribute)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SamlOptions, b.ko.Spec.SamlOptions) {
		delta.Add("Spec.SamlOptions", a.ko.Spec.SamlOptions, b.ko.Spec.SamlOptions)
	} else if a.ko.Spec.SamlOptions != nil && b.ko.Spec.SamlOptions != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.SamlOptions.GroupAttribute, b.ko.Spec.SamlOptions.GroupAttribute) {
			delta.Add("Spec.SamlOptions.GroupAttribute", a.ko.Spec.SamlOptions.GroupAttribute, b.ko.Spec.SamlOptions.GroupAttribute)
		} else if a.ko.Spec.SamlOptions.GroupAttribute != nil && b.ko.Spec.SamlOptions.GroupAttribute != nil {
			if *a.ko.Spec.SamlOptions.GroupAttribute != *b.ko.Spec.SamlOptions.GroupAttribute {
				delta.Add("Spec.SamlOptions.GroupAttribute", a.ko.Spec.SamlOptions.GroupAttribute, b.ko.Spec.SamlOptions.GroupAttribute)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SamlOptions.Metadata, b.ko.Spec.SamlOptions.Metadata) {
			delta.Add("Spec.SamlOptions.Metadata", a.ko.Spec.SamlOptions.Metadata, b.ko.Spec.SamlOptions.Metadata)
		} else if a.ko.Spec.SamlOptions.Metadata != nil && b.ko.Spec.SamlOptions.Metadata != nil {
			if *a.ko.Spec.SamlOptions.Metadata != *b.ko.Spec.SamlOptions.Metadata {
				delta.Add("Spec.SamlOptions.Metadata", a.ko.Spec.SamlOptions.Metadata, b.ko.Spec.SamlOptions.Metadata)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SamlOptions.OpenSearchServerlessEntityID, b.ko.Spec.SamlOptions.OpenSearchServerlessEntityID) {
			delta.Add("Spec.SamlOptions.OpenSearchServerlessEntityID", a.ko.Spec.SamlOptions.OpenSearchServerlessEntityID, b.ko.Spec.SamlOptions.OpenSearchServerlessEntityID)
		} else if a.ko.Spec.SamlOptions.OpenSearchServerlessEntityID != nil && b.ko.Spec.SamlOptions.OpenSearchServerlessEntityID != nil {
			if *a.ko.Spec.SamlOptions.OpenSearchServerlessEntityID != *b.ko.Spec.SamlOptions.OpenSearchServerlessEntityID {
				delta.Add("Spec.SamlOptions.OpenSearchServerlessEntityID", a.ko.Spec.SamlOptions.OpenSearchServerlessEntityID, b.ko.Spec.SamlOptions.OpenSearchServerlessEntityID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SamlOptions.SessionTimeout, b.ko.Spec.SamlOptions.SessionTimeout) {
			delta.Add("Spec.SamlOptions.SessionTimeout", a.ko.Spec.SamlOptions.SessionTimeout, b.ko.Spec.SamlOptions.SessionTimeout)
		} else if a.ko.Spec.SamlOptions.SessionTimeout != nil && b.ko.Spec.SamlOptions.SessionTimeout != nil {
			if *a.ko.Spec.SamlOptions.SessionTimeout != *b.ko.Spec.SamlOptions.SessionTimeout {
				delta.Add("Spec.SamlOptions.SessionTimeout", a.ko.Spec.SamlOptions.SessionTimeout, b.ko.Spec.SamlOptions.SessionTimeout)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SamlOptions.UserAttribute, b.ko.Spec.SamlOptions.UserAttribute) {
			delta.Add("Spec.SamlOptions.UserAttribute", a.ko.Spec.SamlOptions.UserAttribute, b.ko.Spec.SamlOptions.UserAttribute)
		} else if a.ko.Spec.SamlOptions.UserAttribute != nil && b.ko.Spec.SamlOptions.UserAttribute != nil {
			if *a.ko.Spec.SamlOptions.UserAttribute != *b.ko.Spec.SamlOptions.UserAttribute {
				delta.Add("Spec.SamlOptions.UserAttribute", a.ko.Spec.SamlOptions.UserAttribute, b.ko.Spec.SamlOptions.UserAttribute)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Type, b.ko.Spec.Type) {
		delta.Add("Spec.Type", a.ko.Spec.Type, b.ko.Spec.Type)
	} else if a.ko.Spec.Type != nil && b.ko.Spec.Type != nil {
		if *a.ko.Spec.Type != *b.ko.Spec.Type {
			delta.Add("Spec.Type", a.ko.Spec.Type, b.ko.Spec.Type)
		}
	}

	return delta
}
