// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package security_config

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/opensearchserverless"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/opensearchserverless/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/opensearchserverless-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.SecurityConfig{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetSecurityConfigOutput
	resp, err = rm.sdkapi.GetSecurityConfig(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetSecurityConfig", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.SecurityConfigDetail.ConfigVersion != nil {
		ko.Status.ConfigVersion = resp.SecurityConfigDetail.ConfigVersion
	} else {
		ko.Status.ConfigVersion = nil
	}
	if resp.SecurityConfigDetail.CreatedDate != nil {
		ko.Status.CreatedDate = resp.SecurityConfigDetail.CreatedDate
	} else {
		ko.Status.CreatedDate = nil
	}
	if resp.SecurityConfigDetail.Description != nil {
		ko.Spec.Description = resp.SecurityConfigDetail.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.SecurityConfigDetail.IamIdentityCenterOptions != nil {
		f3 := &svcapitypes.CreateIAMIdentityCenterConfigOptions{}
		if resp.SecurityConfigDetail.IamIdentityCenterOptions.GroupAttribute != "" {
			f3.GroupAttribute = aws.String(string(resp.SecurityConfigDetail.IamIdentityCenterOptions.GroupAttribute))
		}
		if resp.SecurityConfigDetail.IamIdentityCenterOptions.InstanceArn != nil {
			f3.InstanceARN = resp.SecurityConfigDetail.IamIdentityCenterOptions.InstanceArn
		}
		if resp.SecurityConfigDetail.IamIdentityCenterOptions.UserAttribute != "" {
			f3.UserAttribute = aws.String(string(resp.SecurityConfigDetail.IamIdentityCenterOptions.UserAttribute))
		}
		ko.Spec.IAMIdentityCenterOptions = f3
	} else {
		ko.Spec.IAMIdentityCenterOptions = nil
	}
	if resp.SecurityConfigDetail.Id != nil {
		ko.Status.ID = resp.SecurityConfigDetail.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.SecurityConfigDetail.LastModifiedDate != nil {
		ko.Status.LastModifiedDate = resp.SecurityConfigDetail.LastModifiedDate
	} else {
		ko.Status.LastModifiedDate = nil
	}
	if resp.SecurityConfigDetail.SamlOptions != nil {
		f6 := &svcapitypes.SamlConfigOptions{}
		if resp.SecurityConfigDetail.SamlOptions.GroupAttribute != nil {
			f6.GroupAttribute = resp.SecurityConfigDetail.SamlOptions.GroupAttribute
		}
		if resp.SecurityConfigDetail.SamlOptions.Metadata != nil {
			f6.Metadata = resp.SecurityConfigDetail.SamlOptions.Metadata
		}
		if resp.SecurityConfigDetail.SamlOptions.OpenSearchServerlessEntityId != nil {
			f6.OpenSearchServerlessEntityID = resp.SecurityConfigDetail.SamlOptions.OpenSearchServerlessEntityId
		}
		if resp.SecurityConfigDetail.SamlOptions.SessionTimeout != nil {
			sessionTimeoutCopy := int64(*resp.SecurityConfigDetail.SamlOptions.SessionTimeout)
			f6.SessionTimeout = &sessionTimeoutCopy
		}
		if resp.SecurityConfigDetail.SamlOptions.UserAttribute != nil {
			f6.UserAttribute = resp.SecurityConfigDetail.SamlOptions.UserAttribute
		}
		ko.Spec.SamlOptions = f6
	} else {
		ko.Spec.SamlOptions = nil
	}
	if resp.SecurityConfigDetail.Type != "" {
		ko.Spec.Type = aws.String(string(resp.SecurityConfigDetail.Type))
	} else {
		ko.Spec.Type = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.ID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetSecurityConfigInput, error) {
	res := &svcsdk.GetSecurityConfigInput{}

	if r.ko.Status.ID != nil {
		res.Id = r.ko.Status.ID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateSecurityConfigOutput
	_ = resp
	resp, err = rm.sdkapi.CreateSecurityConfig(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateSecurityConfig", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.SecurityConfigDetail.ConfigVersion != nil {
		ko.Status.ConfigVersion = resp.SecurityConfigDetail.ConfigVersion
	} else {
		ko.Status.ConfigVersion = nil
	}
	if resp.SecurityConfigDetail.CreatedDate != nil {
		ko.Status.CreatedDate = resp.SecurityConfigDetail.CreatedDate
	} else {
		ko.Status.CreatedDate = nil
	}
	if resp.SecurityConfigDetail.Description != nil {
		ko.Spec.Description = resp.SecurityConfigDetail.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.SecurityConfigDetail.IamIdentityCenterOptions != nil {
		f3 := &svcapitypes.CreateIAMIdentityCenterConfigOptions{}
		if resp.SecurityConfigDetail.IamIdentityCenterOptions.GroupAttribute != "" {
			f3.GroupAttribute = aws.String(string(resp.SecurityConfigDetail.IamIdentityCenterOptions.GroupAttribute))
		}
		if resp.SecurityConfigDetail.IamIdentityCenterOptions.InstanceArn != nil {
			f3.InstanceARN = resp.SecurityConfigDetail.IamIdentityCenterOptions.InstanceArn
		}
		if resp.SecurityConfigDetail.IamIdentityCenterOptions.UserAttribute != "" {
			f3.UserAttribute = aws.String(string(resp.SecurityConfigDetail.IamIdentityCenterOptions.UserAttribute))
		}
		ko.Spec.IAMIdentityCenterOptions = f3
	} else {
		ko.Spec.IAMIdentityCenterOptions = nil
	}
	if resp.SecurityConfigDetail.Id != nil {
		ko.Status.ID = resp.SecurityConfigDetail.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.SecurityConfigDetail.LastModifiedDate != nil {
		ko.Status.LastModifiedDate = resp.SecurityConfigDetail.LastModifiedDate
	} else {
		ko.Status.LastModifiedDate = nil
	}
	if resp.SecurityConfigDetail.SamlOptions != nil {
		f6 := &svcapitypes.SamlConfigOptions{}
		if resp.SecurityConfigDetail.SamlOptions.GroupAttribute != nil {
			f6.GroupAttribute = resp.SecurityConfigDetail.SamlOptions.GroupAttribute
		}
		if resp.SecurityConfigDetail.SamlOptions.Metadata != nil {
			f6.Metadata = resp.SecurityConfigDetail.SamlOptions.Metadata
		}
		if resp.SecurityConfigDetail.SamlOptions.OpenSearchServerlessEntityId != nil {
			f6.OpenSearchServerlessEntityID = resp.SecurityConfigDetail.SamlOptions.OpenSearchServerlessEntityId
		}
		if resp.SecurityConfigDetail.SamlOptions.SessionTimeout != nil {
			sessionTimeoutCopy := int64(*resp.SecurityConfigDetail.SamlOptions.SessionTimeout)
			f6.SessionTimeout = &sessionTimeoutCopy
		}
		if resp.SecurityConfigDetail.SamlOptions.UserAttribute != nil {
			f6.UserAttribute = resp.SecurityConfigDetail.SamlOptions.UserAttribute
		}
		ko.Spec.SamlOptions = f6
	} else {
		ko.Spec.SamlOptions = nil
	}
	if resp.SecurityConfigDetail.Type != "" {
		ko.Spec.Type = aws.String(string(resp.SecurityConfigDetail.Type))
	} else {
		ko.Spec.Type = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateSecurityConfigInput, error) {
	res := &svcsdk.CreateSecurityConfigInput{}

	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.IAMIdentityCenterOptions != nil {
		f1 := &svcsdktypes.CreateIamIdentityCenterConfigOptions{}
		if r.ko.Spec.IAMIdentityCenterOptions.GroupAttribute != nil {
			f1.GroupAttribute = svcsdktypes.IamIdentityCenterGroupAttribute(*r.ko.Spec.IAMIdentityCenterOptions.GroupAttribute)
		}
		if r.ko.Spec.IAMIdentityCenterOptions.InstanceARN != nil {
			f1.InstanceArn = r.ko.Spec.IAMIdentityCenterOptions.InstanceARN
		}
		if r.ko.Spec.IAMIdentityCenterOptions.UserAttribute != nil {
			f1.UserAttribute = svcsdktypes.IamIdentityCenterUserAttribute(*r.ko.Spec.IAMIdentityCenterOptions.UserAttribute)
		}
		res.IamIdentityCenterOptions = f1
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.SamlOptions != nil {
		f3 := &svcsdktypes.SamlConfigOptions{}
		if r.ko.Spec.SamlOptions.GroupAttribute != nil {
			f3.GroupAttribute = r.ko.Spec.SamlOptions.GroupAttribute
		}
		if r.ko.Spec.SamlOptions.Metadata != nil {
			f3.Metadata = r.ko.Spec.SamlOptions.Metadata
		}
		if r.ko.Spec.SamlOptions.OpenSearchServerlessEntityID != nil {
			f3.OpenSearchServerlessEntityId = r.ko.Spec.SamlOptions.OpenSearchServerlessEntityID
		}
		if r.ko.Spec.SamlOptions.SessionTimeout != nil {
			sessionTimeoutCopy0 := *r.ko.Spec.SamlOptions.SessionTimeout
			if sessionTimeoutCopy0 > math.MaxInt32 || sessionTimeoutCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field sessionTimeout is of type int32")
			}
			sessionTimeoutCopy := int32(sessionTimeoutCopy0)
			f3.SessionTimeout = &sessionTimeoutCopy
		}
		if r.ko.Spec.SamlOptions.UserAttribute != nil {
			f3.UserAttribute = r.ko.Spec.SamlOptions.UserAttribute
		}
		res.SamlOptions = f3
	}
	if r.ko.Spec.Type != nil {
		res.Type = svcsdktypes.SecurityConfigType(*r.ko.Spec.Type)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateSecurityConfigOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateSecurityConfig(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateSecurityConfig", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.SecurityConfigDetail.ConfigVersion != nil {
		ko.Status.ConfigVersion = resp.SecurityConfigDetail.ConfigVersion
	} else {
		ko.Status.ConfigVersion = nil
	}
	if resp.SecurityConfigDetail.CreatedDate != nil {
		ko.Status.CreatedDate = resp.SecurityConfigDetail.CreatedDate
	} else {
		ko.Status.CreatedDate = nil
	}
	if resp.SecurityConfigDetail.Description != nil {
		ko.Spec.Description = resp.SecurityConfigDetail.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.SecurityConfigDetail.IamIdentityCenterOptions != nil {
		f3 := &svcapitypes.CreateIAMIdentityCenterConfigOptions{}
		if resp.SecurityConfigDetail.IamIdentityCenterOptions.GroupAttribute != "" {
			f3.GroupAttribute = aws.String(string(resp.SecurityConfigDetail.IamIdentityCenterOptions.GroupAttribute))
		}
		if resp.SecurityConfigDetail.IamIdentityCenterOptions.InstanceArn != nil {
			f3.InstanceARN = resp.SecurityConfigDetail.IamIdentityCenterOptions.InstanceArn
		}
		if resp.SecurityConfigDetail.IamIdentityCenterOptions.UserAttribute != "" {
			f3.UserAttribute = aws.String(string(resp.SecurityConfigDetail.IamIdentityCenterOptions.UserAttribute))
		}
		ko.Spec.IAMIdentityCenterOptions = f3
	} else {
		ko.Spec.IAMIdentityCenterOptions = nil
	}
	if resp.SecurityConfigDetail.Id != nil {
		ko.Status.ID = resp.SecurityConfigDetail.Id
	} else {
		ko.Status.ID = nil
	}
	if resp.SecurityConfigDetail.LastModifiedDate != nil {
		ko.Status.LastModifiedDate = resp.SecurityConfigDetail.LastModifiedDate
	} else {
		ko.Status.LastModifiedDate = nil
	}
	if resp.SecurityConfigDetail.SamlOptions != nil {
		f6 := &svcapitypes.SamlConfigOptions{}
		if resp.SecurityConfigDetail.SamlOptions.GroupAttribute != nil {
			f6.GroupAttribute = resp.SecurityConfigDetail.SamlOptions.GroupAttribute
		}
		if resp.SecurityConfigDetail.SamlOptions.Metadata != nil {
			f6.Metadata = resp.SecurityConfigDetail.SamlOptions.Metadata
		}
		if resp.SecurityConfigDetail.SamlOptions.OpenSearchServerlessEntityId != nil {
			f6.OpenSearchServerlessEntityID = resp.SecurityConfigDetail.SamlOptions.OpenSearchServerlessEntityId
		}
		if resp.SecurityConfigDetail.SamlOptions.SessionTimeout != nil {
			sessionTimeoutCopy := int64(*resp.SecurityConfigDetail.SamlOptions.SessionTimeout)
			f6.SessionTimeout = &sessionTimeoutCopy
		}
		if resp.SecurityConfigDetail.SamlOptions.UserAttribute != nil {
			f6.UserAttribute = resp.SecurityConfigDetail.SamlOptions.UserAttribute
		}
		ko.Spec.SamlOptions = f6
	} else {
		ko.Spec.SamlOptions = nil
	}
	if resp.SecurityConfigDetail.Type != "" {
		ko.Spec.Type = aws.String(string(resp.SecurityConfigDetail.Type))
	} else {
		ko.Spec.Type = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateSecurityConfigInput, error) {
	res := &svcsdk.UpdateSecurityConfigInput{}

	if r.ko.Status.ConfigVersion != nil {
		res.ConfigVersion = r.ko.Status.ConfigVersion
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.IAMIdentityCenterOptions != nil {
		f3 := &svcsdktypes.UpdateIamIdentityCenterConfigOptions{}
		if r.ko.Spec.IAMIdentityCenterOptions.GroupAttribute != nil {
			f3.GroupAttribute = svcsdktypes.IamIdentityCenterGroupAttribute(*r.ko.Spec.IAMIdentityCenterOptions.GroupAttribute)
		}
		if r.ko.Spec.IAMIdentityCenterOptions.UserAttribute != nil {
			f3.UserAttribute = svcsdktypes.IamIdentityCenterUserAttribute(*r.ko.Spec.IAMIdentityCenterOptions.UserAttribute)
		}
		res.IamIdentityCenterOptionsUpdates = f3
	}
	if r.ko.Status.ID != nil {
		res.Id = r.ko.Status.ID
	}
	if r.ko.Spec.SamlOptions != nil {
		f5 := &svcsdktypes.SamlConfigOptions{}
		if r.ko.Spec.SamlOptions.GroupAttribute != nil {
			f5.GroupAttribute = r.ko.Spec.SamlOptions.GroupAttribute
		}
		if r.ko.Spec.SamlOptions.Metadata != nil {
			f5.Metadata = r.ko.Spec.SamlOptions.Metadata
		}
		if r.ko.Spec.SamlOptions.OpenSearchServerlessEntityID != nil {
			f5.OpenSearchServerlessEntityId = r.ko.Spec.SamlOptions.OpenSearchServerlessEntityID
		}
		if r.ko.Spec.SamlOptions.SessionTimeout != nil {
			sessionTimeoutCopy0 := *r.ko.Spec.SamlOptions.SessionTimeout
			if sessionTimeoutCopy0 > math.MaxInt32 || sessionTimeoutCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field sessionTimeout is of type int32")
			}
			sessionTimeoutCopy := int32(sessionTimeoutCopy0)
			f5.SessionTimeout = &sessionTimeoutCopy
		}
		if r.ko.Spec.SamlOptions.UserAttribute != nil {
			f5.UserAttribute = r.ko.Spec.SamlOptions.UserAttribute
		}
		res.SamlOptions = f5
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteSecurityConfigOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteSecurityConfig(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteSecurityConfig", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteSecurityConfigInput, error) {
	res := &svcsdk.DeleteSecurityConfigInput{}

	if r.ko.Status.ID != nil {
		res.Id = r.ko.Status.ID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.SecurityConfig,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
