apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/opensearchserverless.services.k8s.aws_collections.yaml
  - bases/opensearchserverless.services.k8s.aws_securitypolicies.yaml
