// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AccessPolicyType string

const (
	AccessPolicyType_data AccessPolicyType = "data"
)

type CollectionStatus_SDK string

const (
	CollectionStatus_SDK_CREATING CollectionStatus_SDK = "CREATING"
	CollectionStatus_SDK_DELETING CollectionStatus_SDK = "DELETING"
	CollectionStatus_SDK_ACTIVE   CollectionStatus_SDK = "ACTIVE"
	CollectionStatus_SDK_FAILED   CollectionStatus_SDK = "FAILED"
)

type CollectionType string

const (
	CollectionType_SEARCH       CollectionType = "SEARCH"
	CollectionType_TIMESERIES   CollectionType = "TIMESERIES"
	CollectionType_VECTORSEARCH CollectionType = "VECTORSEARCH"
)

type IAMIdentityCenterGroupAttribute string

const (
	IAMIdentityCenterGroupAttribute_GroupId   IAMIdentityCenterGroupAttribute = "GroupId"
	IAMIdentityCenterGroupAttribute_GroupName IAMIdentityCenterGroupAttribute = "GroupName"
)

type IAMIdentityCenterUserAttribute string

const (
	IAMIdentityCenterUserAttribute_UserId   IAMIdentityCenterUserAttribute = "UserId"
	IAMIdentityCenterUserAttribute_UserName IAMIdentityCenterUserAttribute = "UserName"
	IAMIdentityCenterUserAttribute_Email    IAMIdentityCenterUserAttribute = "Email"
)

type LifecyclePolicyType string

const (
	LifecyclePolicyType_retention LifecyclePolicyType = "retention"
)

type ResourceType string

const (
	ResourceType_index ResourceType = "index"
)

type SecurityConfigType string

const (
	SecurityConfigType_saml              SecurityConfigType = "saml"
	SecurityConfigType_iamidentitycenter SecurityConfigType = "iamidentitycenter"
)

type SecurityPolicyType string

const (
	SecurityPolicyType_encryption SecurityPolicyType = "encryption"
	SecurityPolicyType_network    SecurityPolicyType = "network"
)

type StandbyReplicas string

const (
	StandbyReplicas_ENABLED  StandbyReplicas = "ENABLED"
	StandbyReplicas_DISABLED StandbyReplicas = "DISABLED"
)

type VPCEndpointStatus string

const (
	VPCEndpointStatus_PENDING  VPCEndpointStatus = "PENDING"
	VPCEndpointStatus_DELETING VPCEndpointStatus = "DELETING"
	VPCEndpointStatus_ACTIVE   VPCEndpointStatus = "ACTIVE"
	VPCEndpointStatus_FAILED   VPCEndpointStatus = "FAILED"
)
