// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SecurityPolicySpec defines the desired state of SecurityPolicy.
type SecurityPolicySpec struct {

	// A description of the policy. Typically used to store information about the
	// permissions defined in the policy.
	Description *string `json:"description,omitempty"`
	// The name of the policy.
	//
	// Regex Pattern: `^[a-z][a-z0-9-]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The JSON policy document to use as the content for the new policy.
	//
	// Regex Pattern: `[\u0009\u000A\u000D\u0020-\u007E\u00A1-\u00FF]+`
	// +kubebuilder:validation:Required
	Policy *string `json:"policy"`
	// The type of security policy.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Type *string `json:"type"`
}

// SecurityPolicyStatus defines the observed state of SecurityPolicy
type SecurityPolicyStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date the policy was created.
	// +kubebuilder:validation:Optional
	CreatedDate *int64 `json:"createdDate,omitempty"`
	// The timestamp of when the policy was last modified.
	// +kubebuilder:validation:Optional
	LastModifiedDate *int64 `json:"lastModifiedDate,omitempty"`
	// The version of the policy.
	//
	// Regex Pattern: `^([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?$`
	// +kubebuilder:validation:Optional
	PolicyVersion *string `json:"policyVersion,omitempty"`
}

// SecurityPolicy is the Schema for the SecurityPolicies API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type SecurityPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SecurityPolicySpec   `json:"spec,omitempty"`
	Status            SecurityPolicyStatus `json:"status,omitempty"`
}

// SecurityPolicyList contains a list of SecurityPolicy
// +kubebuilder:object:root=true
type SecurityPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityPolicy `json:"items"`
}

func init() {
	SchemeBuilder.Register(&SecurityPolicy{}, &SecurityPolicyList{})
}
