// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SecurityConfigSpec defines the desired state of SecurityConfig.
type SecurityConfigSpec struct {

	// A description of the security configuration.
	Description *string `json:"description,omitempty"`
	// Describes IAM Identity Center options in the form of a key-value map. This
	// field is required if you specify iamidentitycenter for the type parameter.
	IAMIdentityCenterOptions *CreateIAMIdentityCenterConfigOptions `json:"iamIdentityCenterOptions,omitempty"`
	// The name of the security configuration.
	//
	// Regex Pattern: `^[a-z][a-z0-9-]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Describes SAML options in in the form of a key-value map. This field is required
	// if you specify saml for the type parameter.
	SamlOptions *SamlConfigOptions `json:"samlOptions,omitempty"`
	// The type of security configuration.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Type *string `json:"type"`
}

// SecurityConfigStatus defines the observed state of SecurityConfig
type SecurityConfigStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The version of the security configuration.
	//
	// Regex Pattern: `^([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?$`
	// +kubebuilder:validation:Optional
	ConfigVersion *string `json:"configVersion,omitempty"`
	// The date the configuration was created.
	// +kubebuilder:validation:Optional
	CreatedDate *int64 `json:"createdDate,omitempty"`
	// The unique identifier of the security configuration.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The timestamp of when the configuration was last modified.
	// +kubebuilder:validation:Optional
	LastModifiedDate *int64 `json:"lastModifiedDate,omitempty"`
}

// SecurityConfig is the Schema for the SecurityConfigs API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type SecurityConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SecurityConfigSpec   `json:"spec,omitempty"`
	Status            SecurityConfigStatus `json:"status,omitempty"`
}

// SecurityConfigList contains a list of SecurityConfig
// +kubebuilder:object:root=true
type SecurityConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecurityConfig `json:"items"`
}

func init() {
	SchemeBuilder.Register(&SecurityConfig{}, &SecurityConfigList{})
}
